# -*- coding: utf-8 -*-
"""kruskal's algorithm

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jQ57jZ-eTislUhuET4wgWnzCMbsN2Wbf
"""

# Kruskal's Algorithm

def find(parent, i):
    if parent[i] == i:
        return i
    return find(parent, parent[i])


def union(parent, rank, x, y):
    xroot = find(parent, x)
    yroot = find(parent, y)

    if rank[xroot] < rank[yroot]:
        parent[xroot] = yroot
    elif rank[xroot] > rank[yroot]:
        parent[yroot] = xroot
    else:
        parent[yroot] = xroot
        rank[xroot] += 1


def kruskal(vertices, edges):
    edges.sort(key=lambda x: x[2])

    parent = list(range(vertices))
    rank = [0] * vertices

    mst = []
    cost = 0

    for u, v, weight in edges:
        x = find(parent, u)
        y = find(parent, v)

        if x != y:
            mst.append((u, v, weight))
            cost += weight
            union(parent, rank, x, y)

    print("Edges in Minimum Spanning Tree:")
    for u, v, weight in mst:
        print(u, "--", v, "=", weight)

    print("Minimum Cost:", cost)


# Example
vertices = 4

edges = [
    (0, 1, 10),
    (0, 2, 6),
    (0, 3, 5),
    (1, 3, 15),
    (2, 3, 4)
]

kruskal(vertices, edges)